#!/bin/sh
echo exporting SCOT ...
R3trans -w /usr/sap/trans/refresh/logs/export_scot.log  /usr/sap/trans/refresh/scripts/export_SCOT
echo exporting Logical Systems ...
R3trans -w /usr/sap/trans/refresh/logs/export_sale.log  /usr/sap/trans/refresh/scripts/export_SALE
echo exporting SCC4 ...
R3trans -w /usr/sap/trans/refresh/logs/export_scc4.log  /usr/sap/trans/refresh/scripts/export_T000
echo exporting SP01 ... 
R3trans -w /usr/sap/trans/refresh/logs/export_sp01.log  /usr/sap/trans/refresh/scripts/export_SP01
echo exporting SM35 ... 
R3trans -w /usr/sap/trans/refresh/logs/export_sm35.log  /usr/sap/trans/refresh/scripts/export_SM35
echo exporting SM37 ... 
R3trans -w /usr/sap/trans/refresh/logs/export_sm37.log /usr/sap/trans/refresh/scripts/export_SM37
echo exporting SPAD ...
R3trans -w /usr/sap/trans/refresh/logs/export_spad.log  /usr/sap/trans/refresh/scripts/export_SPAD
echo exporting SMLG ..
R3trans -w /usr/sap/trans/refresh/logs/export_smlg.log /usr/sap/trans/refresh/scripts/export_SMLG
echo exporting SM59 ...
R3trans -w /usr/sap/trans/refresh/logs/export_sm59.log /usr/sap/trans/refresh/scripts/export_SM59
echo exporting table TWPURLSVR ...
R3trans -w /usr/sap/trans/refresh/logs/export_TWPURLSVR.log /usr/sap/trans/refresh/scripts/export_TWPURLSVR
echo exporting BD64 ...
R3trans -w /usr/sap/trans/refresh/logs/export_bd64.log /usr/sap/trans/refresh/scripts/export_BD64
echo exporting WE21 ...
R3trans -w /usr/sap/trans/refresh/logs/export_we21.log /usr/sap/trans/refresh/scripts/export_WE21
echo exporting WE20 ...
R3trans -w /usr/sap/trans/refresh/logs/export_we20.log /usr/sap/trans/refresh/scripts/export_WE20
