#!/bin/sh
echo importing SP01 ... 
R3trans -w /usr/sap/trans/refresh/logs/import_sp01.log  /usr/sap/trans/refresh/scripts/import_SP01
echo importing SM35 ... 
R3trans -w /usr/sap/trans/refresh/logs/import_sm35.log  /usr/sap/trans/refresh/scripts/import_SM35
echo importing SM37 ... 
R3trans -w /usr/sap/trans/refresh/logs/import_sm37.log /usr/sap/trans/refresh/scripts/import_SM37
echo importing SPAD ...
R3trans -w /usr/sap/trans/refresh/logs/import_spad.log  /usr/sap/trans/refresh/scripts/import_SPAD
echo importing SMLG ..
R3trans -w /usr/sap/trans/refresh/logs/import_smlg.log /usr/sap/trans/refresh/scripts/import_SMLG
echo importing SM59 ...
R3trans -w /usr/sap/trans/refresh/logs/import_sm59.log /usr/sap/trans/refresh/scripts/import_SM59
echo importing table TWPURLSVR ...
R3trans -w /usr/sap/trans/refresh/logs/import_TWPURLSVR.log /usr/sap/trans/refresh/scripts/import_TWPURLSVR
echo importing BD64 ...
R3trans -w /usr/sap/trans/refresh/logs/import_bd64.log /usr/sap/trans/refresh/scripts/import_BD64
