#!/bin/sh
R3trans -w /usr/sap/trans/refresh/logs/import_scot.log  /usr/sap/trans/refresh/scripts/import_SCOT 
R3trans -w /usr/sap/trans/refresh/logs/import_sale.log  /usr/sap/trans/refresh/scripts/import_SALE 
R3trans -w /usr/sap/trans/refresh/logs/import_scc4.log  /usr/sap/trans/refresh/scripts/import_T000 
R3trans -w /usr/sap/trans/refresh/logs/import_sp01.log  /usr/sap/trans/refresh/scripts/import_SP01 
R3trans -w /usr/sap/trans/refresh/logs/import_sm35.log  /usr/sap/trans/refresh/scripts/import_SM35 
R3trans -w /usr/sap/trans/refresh/logs/import_sm37.log /usr/sap/trans/refresh/scripts/import_SM37
R3trans -w /usr/sap/trans/refresh/logs/import_spad.log  /usr/sap/trans/refresh/scripts/import_SPAD
R3trans -w /usr/sap/trans/refresh/logs/import_smlg.log /usr/sap/trans/refresh/scripts/import_SMLG
R3trans -w /usr/sap/trans/refresh/logs/import_sm59.log /usr/sap/trans/refresh/scripts/import_SM59
R3trans -w /usr/sap/trans/refresh/logs/import_TWPURLSVR.log /usr/sap/trans/refresh/scripts/import_TWPURLSVR
R3trans -w /usr/sap/trans/refresh/logs/import_bd64.log /usr/sap/trans/refresh/scripts/import_BD64
R3trans -w /usr/sap/trans/refresh/logs/import_we21.log /usr/sap/trans/refresh/scripts/import_WE21
R3trans -w /usr/sap/trans/refresh/logs/import_we20.log /usr/sap/trans/refresh/scripts/import_WE20
